---
title: 사전투표 상수의 비밀
author: Seokjin Woo
date: '2020-04-21'
categories:
  - R
tags:
  - R Markdown
slug: 사전선거-조작-논란-정리
---


울 아버지가 사전투표가 조작되었다고 하신다. 특히 경합지역 사전투표에서 이상한 상수가 나온다고 어디 유튜브에서 들으셨다고 얘기하신다. 할아버지들 카톡에 돌아다는 것 같은데, 데이터 밥 먹는 선수로서 안들여다 볼 수 없었다.

몇 유튜브 상황을 보니 크게 보면 두 가지 이슈이다. 

1. 사전투표 관내/관외 비율이 경합지에서 소수점 몇 자리만 빼고 동일한 숫자가 나온다. 이거 조작의 흔적 아니냐? 이상하니 점검해보자. 프로듀스 뭐시기들도 이렇게 시작해서 나중에 조작 밝혀졌다. 어여 소송해서 사전투표함 까보자. 그러니까 뭔지는 모르겠지만 이상한 패턴이 발견되었으니 조사해보자.

2. 사전투표와 본투표 결과가 이렇게 차이날 수 있느냐? 본투표만으로 했을 때 미통당이 120개 이상 먹어야 하는데 억울하다. 사전투표 결과에서 민주당이 압도적이라면, 본투표에서도 그래야 하는 거 아니냐? 일주일 사이에 뭔 대단한 일이 있었다고 그 차이가 발생하느냐?


내가 보았을 때, 2번 이슈는 일종의 선택(selection)의 문제인데, 특정 성향을 가진 사람들이 사전투표를 했으면 본투표와 차이가 날 수 있다. 사회과학을 하는 사람들은 대체로 자기 선택에 대한 이해도가 높은 편인데, 일반인들을 그렇지 않을 수도 있겠다. 사전투표와 본투표는 서로 독립적인 시행이 아니고, 당연히 유권자들의 선택에 따른 시점간 배분 현상이기 때문에 사전투표와 본투표 결과가 다르다고 해서 놀라운 사실은 아니겠다. 

보통 민주당이 사전, 미통당이 본투표를 이겼을 거라고 예상이 되는데, 항상 그렇지는 않더라. 우리 동네 구로을을 보니 윤건영 후보가 김용태 후보를 본투표에서는 크게 이겼지만, 사전투표에서는 오히려 크게 이겼더라. 어쨋든 이건 지역마다 다르기 때문에 이걸 설명해보라고 윽박지르면 딱히 힐 말은 없다.


이슈 1로 가보자. 이슈 1도 복잡한 문제는 아니고 단순한 산수 문제와 정확도(표준편차)의 문제이다.   

설명을 위해 다음과 같이 정의해보자. 

관내 사전투표를 $V^i$, 관외 사전투표를 $V^o$ 라고 정의해보자. 그러면 후보자 $k$의 관외/관내 사전투표의 비율은 아래와 같이 쓸 수 있다.


$$ R_k = \frac{V_k^o}{V_k^i} $$

위 관외/관내 비율 $R_k$은 후보자별로 유사할 이유가 별로 없다. 특정한 경우가 아니라면, 위 비율이 후보자 별로 유사하다면, 특정한 사건이 발생했다고 보는 것이 합리적이다. 문제는 어떤 사건이 발생하면 위 $R_k$가 유사해질 것인가를 생각해보는 것이다. 



위 식은 간단한 산수를 통해서 다음과 같이 다시 쓸 수 있다. 분자와 분모에 동일한 숫자를 나누고 곱하는 과정이다. 예컨대 후보자 1의 관외/관내 비율을 다시 표시해보자. 

$$ 
\begin{eqnarray}
  \frac{V_1^o}{V_1^i} 
   &=& \frac{V_1^o/(V_1^o + V_2^o) \times (V_1^o + V_2^o)}{V_1^i/(V_1^i + V_2^i) \times (V_1^i + V_2^i) }  \\
   &=& (\frac{v_1 ^o }{v_1 ^i}) \times (\frac{V_1^o + V_2^o}{V_1^i + V_2^i}  )
\end{eqnarray}   
  $$


여기에서 $v_1 ^i$는 후보자 1의 관내투표 중 득표비율이고, $v_1 ^o$는 후보자 1의 관외투표 중 득표비율이다. 

만약 $\frac{v_1 ^o }{v_1 ^i}$이 1과 유사하다면, 즉 관외 득표율과 관내 득표율이 유사하다면, 관내/관외 득표 비율은 

$$ \frac{V_1^o}{V_1^i} 
   \approx \frac{V_1^o + V_2^o}{V_1^i + V_2^i} $$ 


두 후보의 경합이 심한 경우 후보 1의 $\frac{v_1 ^o }{v_1 ^i} \approx 1$이면 후보 2의 경우도 

$$ \frac{v_2 ^o }{v_2 ^i} \approx 1 $$ 


이 된다. 후보자 1이 관외와 관내에서 30%를 받았으면, 후보자 2는 관외와 관내에서 70%를 받게 된다. 그래서 득표율의 비율은 역시 1이 된다. 

그러면 다음의 관계가 자연스럽게 도출된다. 두 후보의 관외/관내 비율은 관외 및 관내 투표자수에 따라 결정되는 것이지, 각 후보가 어떤 득표를 받았는지와는 무관해진다. 즉,


$$ \frac{V_1^o}{V_1^i} 
   \approx \frac{V_1^o + V_2^o}{V_1^i + V_2^i} \approx \frac{V_2^o}{V_2^i} $$ 
   
   
   
이 된다.

따라서 경합지역의 관내/관외 투표자의 성향이 유사하다면 관내/관외 득표 비율은 유사한 숫자가 나오게 된다.


예들 들어, 연수을의 경우 정일영 후보의 경우 관외/관내 투표 비율은 39.15%, 민경욱 후보의 경우 39.35%가 나온다. 이 얼마나 의심하기 좋은 숫자인가.

하지만, 관외투표 중 정일영 후보는 58.1%를 관낸투표 중 58.2%(두 사람만 고려했을 때)을 얻어 $\frac{v_1^o}{v_1^i} \approx 1$이 된다. 민경욱 후보도 마찬가지이다. 그렇기 때문에 39로 대표되는 숫자는 사실 관외투표자합/관내투표자합인 약 39% 근처에서 형성되는 것이다. 별 거 없다. 딱 요 관계이다. 


남은 문제는 정확도인데, 이는 투표자의 수가 많아지면 $\frac{V_1^o}{V_1^i}$과 $\frac{V_2^o}{V_2^i}$의 편차는 충분히 작아질 수 있다. 예를 들어, 본인이 시뮬레이션을 해보니, 1만 투표의 경우에 퍼센티지로 소수자리까지의 표준편차를 구할 수 있었다.


국가를 생각하는 아버지의 마음을 이해는 하지만, "내가 생각할 때 이상하다"는 것과 "조작의 입증"과는 큰 괴리가 있음을 오늘 퇴근하면서 말씀드려야겠다.









   
