---
title: visualization 2
author: Seokjin Woo
date: '2020-06-17'
slug: visualization-2
categories:
  - R
tags:
  - R Markdown
---

그래프를 그리다보면 Y-축의 단위가 애매해지는 경우가 있다.

보통은 가독성이 높은 축을 선택하는 것이 좋다.

**좋은 경우**

* 0, 1, 2, 3, 4, 5
* 0, 2, 4, 6, 8
* 0, 5, 10, 15, 20 

등

```{r, message=FALSE}
# 라이브러리를 로딩합니다.
library(tidyverse)
library(AER)
library(patchwork)

data("USMacroSWM")


df <- data.frame(date=as.Date(as.yearmon(time(USMacroSWM))), 
                 as.matrix(USMacroSWM))


df %>% 
  filter(date >= as.Date(as.yearmon(1980, 1))) %>% 
  ggplot(aes(x = date, y = cpi)) +
  geom_line() -> p1

df %>% 
  filter(date >= as.Date(as.yearmon(1980, 1))) %>% 
  ggplot(aes(x = date, y = cpi)) +
  geom_line() +
  scale_y_continuous(breaks = seq(80,190,10)) -> p2

df %>% 
  filter(date >= as.Date(as.yearmon(1980, 1))) %>% 
  ggplot(aes(x = date, y = cpi)) +
  geom_line() +
  scale_y_continuous(breaks = seq(80,190,10)) +
  scale_x_date(breaks = '5 years', labels = scales::date_format("%Y")) -> p3




(p1 | p2) /   p3

```

첫 번째 그림은세로축의 증감을 25로, 두 번째 글미은 증감을 10씩 한 것이다.

세 번째 그림은 X-축의 증감을 5년단위로 표시한 것이다.

문제는 바탕과 그리드인데, 다음 포스팅에서 좀 더 설명하겠지만서도 그리드 선은 대체로 간단하면 좋다.

값을 체크할 필요가 있어 참조선이 필요한 경우를 제외하면 대체로 없애는 것이 좋다.



```{r, message=FALSE}


df %>% 
  filter(date >= as.Date(as.yearmon(1980, 1))) %>% 
  ggplot(aes(x = date, y = cpi)) +
  geom_line() +
  scale_y_continuous(breaks = seq(0,200,20),
                     limits = c(0, 200)) +
  scale_x_date(breaks = '5 years', labels = scales::date_format("%Y")) +
  theme(
    panel.grid.major.x =  element_blank(),
    panel.grid.major.y =  element_line(size = 0.5, color = "gray"),
    panel.background   =  element_blank()
        ) -> p1
  

 p1

```



