---
title: 소득인정액이란?
author: Seokjin Woo
date: '2020-04-01'
slug: 소득인정액이란
categories:
  - R
tags:
  - R Markdown
---

# 소득인정액에 대해서 알려주마
*version 1.2*


## 개요

대통령님께서 가구 70%에 대해 재난지원금을 지원하겠다고 발표하셨다. 
하지만 가구의 70%라는 것이 말은 쉽지 구체적으로 특정되지 않기 때문에 그걸 구체화 시키는 작업이 필요하다. 그 작업을 복지부가 맡아서 하고 있다. 복지부는 전통적으로 형평성을 중시여기기 때문에 소득 대신 소득인정액이라는 개념을 이용하여 재난지원금 지원 기준을 마련하려고 하고 있다. 

소득인정액이라는 것은 일종의 보이지 않는 경제 능력이라는 걸 구체화 시킨 것이다. 우리나라는 저소득층 지원을 위해 소득인정액을 사용하고 있기 때문에 저소득층 소득 현황을 비교적 잘 반영하도록 산식이 만들어져 있다. 건보에서도 지역가입자를 위해, 국가장학금의 경우에는 장학금을 지급을 위해 일종의 소득인정액을 사용하고 있다.

소득인정액을 계산하기 위해서는 소득과 재산에 대한 정보가 필요하다. 우리 복지제도는 신청주의를 따르고 있기 때문에, 복지제도를 이용하기 위해 신청하지 않은 사람의 소득과 재산을 확인하기는 기본적으로어렵다. 복지로 사이트에서 자기 소득과 재산을 기입하면 공식에 의해서 시산을 해 볼 수는 있다. 하지만, 공식적인 것은 아니며 공식적인 소득인정액은 신청했을 때 가능해진다. 

그렇기 때문에 소득분포를 파악하기 위해 지역가입자에 대해서 정보가 파악되어 있는 건보자료를 이용한다든지, 복지 수급자에 대해서 파악이 되어 있는 행복이음을 이용하겠다는 얘기가 나오는 것이다. 

잘 생각해보자. 기본적으로 소득인정액 기준으로 70%의 가구가 어떤 수준인지를 알려고 하면, 전 가구에 대해 소득인정액을 다 계산해보아야 한다.이 말은 전가구가 신청을 하고, 그걸 기반으로 사회보험, 국세청, 금융기관 등으로부터 소득, 재산 자료를 가져올 때 가능하다는 것이다. 최소한 표집을 해서 표집된 가구의 동의를 받고 가구의 소득인정액 분포를 파악해야 한다. 이 때에도 전수가 아니기 때문에 표본오차는 필연적으로 발생한다. 70% 기준을 발표했을 때, 원래는 70%에 해당하지만, 발표된 기준으로는 재난지원금을 받지 못하는 가구가 발생할 수 있다는 얘기이다. 

소득인정액 계산할 때 소득과 재산을 소득으로 환산한 금액이 사용된다. 소득이야 분명한 것이지만, 재산을 소득으로 환산할 때 쓰이는 소득환산율은 저소득층을 위해서 만들어 놓은 것이기 때문에 전국민에게 적용하면 불복하는 사람들이 아주 많을 것이다.

어쨋든 소득인정액이 무엇인지 알아보자.

*****

## 소득인정액의 정의

`국민기초생활보장법 제2조(정의)의 9항`을 보면 

> "**소득인정액**"이란 보장기관이 급여의 결정 및 실시 등에 사용하기 위하여 산출한 개별가구의 `소득평가액`과 `재산의 소득환산액`을 **합산**한 금액을 말한다.

이렇게 정의되어 있다. 

그러니까, 다음과 같이 소득인정액  AI 을 써 볼 수 있다. 

$$AI = IE + IA$$

* $AI$: 소득인정액
* $IE$: 소득평가액
* $IA$: 재산의 소득환산액

예를 들어보자. 
소득인정액은 월단위로 계산을 하기 때문에 세전 월 500만원이고 다른 소득이 없으면, 당신의 소득평가액은 일단 500만원이 된다.  

여기에 재산을 소득으로 환산하여 더해야 한다. 예컨대 당신이 6억짜리 아파트에 살고 있다고 해보자. 대출은 없다고 가정하자. 

그러면 주거하는 재산에 대한 소득환산율 대략 1%(정확히는 1.04%)인 600만원을 더해, 월 1천 1백만원이 당신의 소득인정액이 된다. 

만약통장에 1천만원 정도 예금이 있으면 대략 6%(정확히는 6.26%)인 60만원이 더해진 1천 160만원이 당신의 소득인정액이 된다. 

암튼, 이런 개념으로 소득인정액을 계산하는 것이다. 

***

## 소득평가액의 계산

좀 더 구체적으로 소득평가액을 어떻게 계산하는지 알아보자. `동법 6조3`은 **소득인정액**의 산정을 규정하고 있다.

일단 다음의 소득을 합하여 **소득평가액**을 계산한다.

1. 근로소득: 그래, 니네가 직장에서 번 돈이다.
2. 사업소득: 이건 사업해선 번 돈이다(매출 아니다)
3. 재산소득: 약간 까리한데, 임대사업자 소득은 사업소득이나 여기에 포함되어 있다. 
4. 이전소득: 이건 사적/공적 이전소득

이렇게 합해진 데서 정해진 금액을 차감할 수 있다. 다음의 조건에 맞으면 된다. 

1. 장애, 질병, 양육 등 가구 특성에 따른 지출요인
2. 근로 유인을 위한 요인
3. 그 밖의 추가지출 요인

위 항목을 차감하고 나면 소득평가액($IE$)이 결정된다. $IE$는 아래와 같이 쓸 수 있다. 


$$IE = (I_w + I_b + I_a + I_t) - (C_d + C_w + C_o)$$

그러니까, 니가 번돈에서 고정적으로 소요되는 비용을 반영해서 이른바 소득평가액이 결정된다.

아까 위에서 세전 500만원이라고 했는데, 혹시 인정되는 지출요인이 있다면 그걸 빼준다. 하지만, 이번 재난지원금 상황에서는 이걸 고려해줄 것 같지는 않다. 그리니, 일단 잊어보자. 


*****

## 재산의 소득환산액

이렇게 소득평가액이 계산되면 그 다음에는 재산을 소득으로 환산해야 한다.

**재산의 소득환산액**을 산출해보자. 재산은 법에 따르면 아래와 같이 구분한다. 

1. 일반재산(주거용과 일반재산으로 다시 구분)
2. 금융재산
3. 자동차 

위 내역을 반영하는데, 개별가구의 **재산가액**에서 기본재산액 및 부채를 뺀 금액에 소득환산율을 곱해서 정한다. 일종의 순자산 개념이다. 나름 합리적이다. 

계산의 편의를 위해 기본재산액은 일단 무시해보자. 아까 위에서 6억자리 아파트에 대출이 2억 끼어 있으면 그 가치는 4억이 된다. 4억의 1%인 400만원이 주거재산의 소득환산액이 된다.


위의 산식을 고려하면 일반적으로 다음과 같이 재산의 소득환산액이 결정된다. 

$$IA = [ (A_g + A_m + A_c )-D_b - D_d ] \times \alpha$$


여기에서 $\alpha$ 는 재산 종류마다 다르게 적용될 수 있다. 위 산식의 경우 법에는 명확하게 제시되어 있는데, 시행령과 고시를 보면 재산 종류별로 부채와 기본재산액을 빼고 서로 다른 $\alpha$를 적용할 수 있게 되어 있다. 

* 법상으로 보면 재산가액에서 부채와 기본공제액을 제한 후에 소득환산율을 곱하도록 되어 있는데, 소득환산율과 관련된 고시를 보면 각 재산별로 소득환산율을 적용하도록 되어 있어 시행령과 고시의 불일치가 발생하고 있다. 이를 시정하는 방법은 각 재산별로 부채 및 공제를 적용하여 해당 재산의 소득환산율을 곱해서 계산해야 한다(`기초생보 시행령 제5조의 4`)


*****

## 소득환산율

이놈의 소득환산율이 어떤지 다시 살펴보자. 

구체적으로는 **국민기초생활 보장법상 재산의 소득환산율 고시**에 따라 정하고 있다(보건복지부 고시). 환산율은 아래의 표를 참조하자.


<center>

| 주거용 재산 | 일반재산    | 금융재산    | 승용차      |
|-----------|-----------|-----------|-----------|
| 월 1.04%    |  월 4.17%   | 월 6.26%    |  월 100%    |

</center>


위의 숫자가 뭔지 궁금해 하는 사람들이 있을 것 같은데, 위 재산을 털어서 생활비를 썼을 때, 얼마만에 다 털어쓸 수 있는지를 적용한 숫자이다. 예컨대 일반재산을 유동화 해서 24개월만에 털어먹고(1/24), 금융재산은 16개월만에 털어먹는다는 계산이다. 

경제학자로서는 도통 이해할 수 없는 환산율이다. 예컨대, 1천만원 예금이 있으면 대략 월 60만원, 년간 72%인 720만원이 있다고 보는 셈인데, 참으로 이해할 수 없는 계산이다. 우리가 보통은 원금은 내버려 두고 거기에서 흘러나오는 이자를 소득으로 보는데. 어쨋든 그렇다. 

***

## 향후 논의

현재 논의되고 있는 소득인정액은 아마도 이걸 준용해서 결정될 것 같다. 아침 종편에서 들으니 아래와 유사한 안이 논의되고 있다고 하더라.

소득인정액의 간편한 계산을 위해서 포함 소득은

- 소득평가액
- 주거용 재산
- 혹은 일반재산

까지 포함하고

- 금융자산
- 승용차

는 제외하는 방향으로 논의가 진행되고 있는 것 같다. 


**이게 골때리는 것이 위기에 닥쳤을 때 유동화가 쉬운 금융재산은 산식에서 제외하고, 유동성이 낮은 재산은 포함시키는 아주 공무원스러운 일을 하고 있는 것이다.**

***

다음에는 기준 중위소득으로 찾아뵙겠다.





