---
title: 바챠트에 레이블 붙이기
author: Seokjin Woo
date: '2020-05-19'
slug: test
categories:
  - R
tags:
  - R Markdown
---

이 포스트는 R-blogger 중 (https://thomasadventure.blog/posts/labels-ggplot2-bar-chart/)에 게시된 내용을 정리한 것이다.

논문이나 연구보고서를 작성하다보면 바챠트를 종종 사용하게 되는데,
바에다 값을 나타내는 레이블을 잘 붙여두면 가독성이 많이 향상된다.

먼저 사용할 패키지를 로딩한다. 

```{r, message=FALSE}
library(dplyr)
library(ggplot2)
library(ggcharts)
```

그리고 바챠트에 사용할 데이터를 만든다.

```{r, message = FALSE}
dreaded_lang <- tibble::tribble(
  ~language, ~pct,
  "VBA", 75.2,
  "Objective-C", 68.7,
  "Assembly", 64.4,
  "C", 57.5,
  "PHP", 54.2,
  "Erlang", 52.6,
  "Ruby", 49.7,
  "R", 48.3,
  "C++", 48.0,
  "Java", 46.6
)

```

이렇게 만들어진 자료를 이용하여 ``bar_chart()``를 이용하여 다음과 같이 바챠트를 그리자.


```{r, message = FALSE}
chart <- dreaded_lang %>% 
  bar_chart(language, pct) %>% 
  print()
```

여기에다가 레이블을 붙여보자. ``geom_text()`` 혹은 ``geom_label()``을 사용할 수 있지만, 일단 ``geom_text()``를 사용해보자.



```{r, message = FALSE}
chart +
  geom_text(aes(
    x = language,
    y = pct,
    label = pct
    ))
```


레이블의 위치가 기본적으로 y값의 중간에 위치하도록 되어 있기 때문에 위치를 ``hjust``를 이용해서 정렬을 해줄 수 있다.


```{r, message = FALSE}
chart +
  geom_text(aes(label = pct, hjust = -0.5)) +
  ylim(NA,100)
```

``hjust`` 값이 양수인 경우 바의 안쪽으로 레이블리 들어간다.

```{r, message = FALSE}
chart +
  geom_text(aes(label = pct, 
                hjust = 1.2),
            color = "white"
            )
```


퍼센트를 붙이는 것도 가능하다.


```{r, message = FALSE}
dreaded_lang %>%
  mutate(label = sprintf("%1.1f%%", pct)) %>%
  bar_chart(language, pct, highlight = "R", bar_color = "black") +
  geom_text(aes(label = label, hjust = -0.1), size = 5) +
  scale_y_continuous(
    limits = c(0, 100),
    expand = expansion()
  ) +
  labs(
    x = NULL,
    y = "Percentage",
    title = "Top 10 Most Dreaded Programming Languages",
    subtitle = "*R Placed 8th*",
    caption = "Source: Stackoverflow Developer Survey 2019"
  ) +
  theme(
    axis.text.x = element_blank(),
    axis.line.x = element_blank(),
    axis.ticks.x = element_blank()
  )
```


