---
title: 4차 재난지원금은 저임금 노동자에게도
author: Seokjin Woo
date: '2021-01-13'
categories:
  - R
tags:
  - R Markdown
slug: 4th-emergency-disaster-aid
---


## 4차 재난지원금은 저임금 노동자에게도

http://www.hani.co.kr/arti/opinion/column/978445.html

코로나19 확산의 세번째 파동이 다행히 고비를 넘고 있는 것 같다. 이번 확산세는 지난 1차 확산 때보다 길고 넓고 깊다. 1차와 2차 확산기에는 특정 클러스터가 있어 집중 방역으로 통제가 가능했다. 이번 3차 확산세는 수도권뿐만 아니라 전국적으로도 광범위하게 퍼져 있어 단기간에 방역 효과를 내기는 어려워 보인다.

방역에 협조하는 국민들은 어려운 시간을 보내고 있다. 특히 영업제한을 받고 있는 자영업자 및 소상공인의 피해는 상상을 초월한다. 방역 협조를 위한 이들의 희생은 우리 방역을 지탱하는 버팀목이 되고 있다. 이에 지난 2차와 3차 재난지원금은 소상공인과 자영업자에 대한 지원을 중심으로 설계되었다. 여기에 이른바 특수고용직에 대한 지원까지 포함되었다.

그럼에도 지원 규모와 설계에는 아쉬운 부분이 있다. 이번 3차 맞춤형 피해지원대책은 그 규모가 9조원 이상으로 발표는 되었지만, 잘 뜯어보면 재난지원금 성격의 지원은 5조원에 못 미친다. 소상공인 버팀목자금 4조1천억원, 소상공인의 재도전·취업 장려금 1천억원, 특수고용노동자 등에 대한 소득안정지원금 5천억원 등에 그친다. 나머지는 대체로 기존 사업을 조기 집행하거나 확대 집행하는 수준이다.

지원방식은 선별적 보편지원 방식을 따르고 있다. 영업제한 강도에 따라 지원대상을 선별하되 선별된 업종에 대해서 대체로 동일한 금액을 지원하는 방식이다. 소상공인 버팀목자금의 경우 100만원을 기본으로 지원하고, 집합제한 업종은 추가로 100만원, 집합금지 업종은 여기에 100만원을 더 추가하는 방식이다. 지원대상은 2019년 대비 지난해 매출이 감소한 연매출 4억원 이하로 한정하였다. 소득이 감소한 특수형태근로종사자와 프리랜서에게도 기존 수혜자는 50만원, 신규 수혜자는 심사를 거쳐 100만원이 지원된다.
2차, 3차 지원에서 빠진 지원대상이 있는데 저임금 노동자이다. 

코로나19 확산 시기에 월급을 받는 임금 근로자는 상대적으로 고용이 안정적이어서 소득에 타격을 입지 않아 지원이 자영업자에게 집중되었다. 하지만 김용기 일자리위원회 부위원장의 한 언론 인터뷰에 따르면 지난해 11월 고용동향은 악화되었고, 12월 지표도 악화되었을 것으로 예상된다. 경기가 위축되고 소상공인과 자영업자들이 피해를 봤다면, 당연히 거기에 종사하는 노동자들의 일자리도 온전할 리 없다.

자영업자의 경우 방역 정책에 영향을 받았는지 여부와 부가가치세를 살펴보면 피해규모를 대략 가늠할 수 있다. 하지만 임금 노동자의 경우에는 상대적으로 현 소득 상황을 파악하기 어렵다. 피해 규모 추산이 어렵다는 얘기다. 다행히 지금은 연말정산 시즌이다. 대략 1900만명의 임금 근로자는 2020년 근로소득을 합쳐 월급 받을 때 납부한 세액에 비해 세금을 더 내야 하는지 아니면 돌려받아야 하는지를 결정하는 정산을 하게 된다. 이 과정에서 코로나19를 거치면서 노동자가 지난 한해 얼마나 피해를 입었는지를 비교적 정확히 계량할 수 있다. 이를 바탕으로 저소득 임금 근로자에 대한 재난지원금 지원 방안을 모색해야 한다.

최근에 발표되는 1차 재난지원금의 지원 효과를 분석한 연구들에 따르면, 저소득층에 지원을 집중하는 것이 정책 측면에서 효과적이면서 효율적이다. 연말정산 정보를 활용하면 소득에 따라 차등지원을 하는 경우 보편적인 요소와 선별적인 요소를 동시에 반영할 수 있다.

예를 들어, 소득금액 3천만원까지는 인적공제 규모에 따라 정해진 액수를 100% 지급하고, 6천만원까지는 일정 금액을 감액하는 차등지급 방식으로 재난지원금을 지원할 수 있다. 여기에 소득 감소분에 대해서는 일정 부분 추가지원을 할 수 있다. 이렇게 되면 2019년 기준 연말정산을 하는 노동자의 82% 정도가 혜택을 볼 수 있고, 부양가족까지 고려하면 대략 3천만명에게 지원을 해줄 수 있다.

지난 1차 재난지원금 지급 때 모든 국민에게 먼저 지급하고 나중에 정산하는 방식이 제안되기도 했었다. 그때는 정부가 주었다 뺏는 정책은 안 된다는 반대가 있었다. 지금은 연말정산 정보를 이용해 뺏는 과정 없이 재난지원금을 주기만 하면 된다. 또한 보편이냐 선별이냐는 지루하면서도 비생산적인 논쟁을 비켜갈 수도 있다. 연말정산 정보를 이용한 저임금 노동자에 대한 재난지원금 지원 방안은 이번 정부가 내세운 디지털 뉴딜 중 스마트한 정부의 좋은 정책 사례가 될 것이다.

 